/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assistant_jabbis;
import databaseConnection.databaseConnect;
import java.sql.PreparedStatement;
import com.formdev.flatlaf.FlatDarkLaf;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author USER
 */
public class archWindow extends javax.swing.JFrame {
    private Connection con;
    
    /**
     * Creates new form archWindow
     */
    public archWindow() {

        initComponents();
        con = databaseConnect.getConnection();
        loadData();
    }
    private void loadData() {
    // TODO add your handling code here:
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
       model.setRowCount(0); // Clear existing data
       try {
           // Query to get the user ID from the setjabbis table
           String query1 = "SELECT * FROM setjabbis";
           PreparedStatement prstmt = con.prepareStatement(query1);
           ResultSet rs1 = prstmt.executeQuery();

           // Check if there are results
           if (rs1.next()) {
               int userid = rs1.getInt("userid");

               // Query to get tasks from the archive table for the specific user
               String query = "SELECT * FROM archive WHERE userid = ?";
               PreparedStatement pstmt = con.prepareStatement(query);
               pstmt.setInt(1, userid);
               ResultSet rs = pstmt.executeQuery();

               // Loop through the results and add them to the table model
               while (rs.next()) {
                   // Retrieve data from the database
                   int id = rs.getInt("id");
                   String todo = rs.getString("task");
                   String subject = rs.getString("subject");
                   String deadline = rs.getString("CompleteDate");
                   // Add row to the table model
                   model.addRow(new Object[]{id, todo, subject, deadline});
               }
           } else {
               System.out.println("No user found in setjabbis.");
           }
       } catch (Exception e) {
           System.out.println("Error: " + e.getMessage());
       }
   }   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        searchfarch = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        searcharchbtn = new javax.swing.JButton();
        backbtn = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(60, 63, 65));
        jTable1.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(0, 255, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "Task", "Subject", "Do", "Deadline"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jPanel11.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 860, 360));

        jLabel8.setBackground(new java.awt.Color(102, 102, 102));
        jLabel8.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 255, 51));
        jLabel8.setText("Archive Task");
        jPanel11.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        searchfarch.setBackground(new java.awt.Color(60, 63, 65));
        searchfarch.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        searchfarch.setForeground(new java.awt.Color(0, 255, 0));
        searchfarch.setBorder(null);
        searchfarch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchfarchActionPerformed(evt);
            }
        });
        jPanel11.add(searchfarch, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 280, 40));

        jSeparator8.setForeground(new java.awt.Color(0, 255, 0));
        jPanel11.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 280, 30));

        searcharchbtn.setBackground(new java.awt.Color(51, 51, 51));
        searcharchbtn.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        searcharchbtn.setForeground(new java.awt.Color(0, 255, 51));
        searcharchbtn.setText("Search");
        searcharchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searcharchbtnActionPerformed(evt);
            }
        });
        jPanel11.add(searcharchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 40));

        backbtn.setBackground(new java.awt.Color(51, 51, 51));
        backbtn.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        backbtn.setForeground(new java.awt.Color(0, 255, 0));
        backbtn.setText("BACK");
        backbtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        backbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbtnMouseClicked(evt);
            }
        });
        jPanel11.add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, -1, -1));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/vecteezy_computer-processor-chip-technology-background-design-blue_11641945.jpg"))); // NOI18N
        jLabel16.setText("czxzxczxcxzc");
        jPanel11.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 900, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchfarchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchfarchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchfarchActionPerformed

    private void searcharchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searcharchbtnActionPerformed
        // TODO add your handling code here:
        // Retrieve the search input
        String userInput = this.searchfarch.getText().trim();

        // Clear existing data in the table
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);

        try {
            // Establish a database connection
            con = databaseConnect.getConnection();

            // Define a query to search for alarms matching the user input
            String query = "SELECT * FROM archive WHERE list LIKE ? OR subject LIKE ?";
            PreparedStatement prstmt = con.prepareStatement(query);
            prstmt.setString(1, "%" + userInput + "%");
            prstmt.setString(2, "%" + userInput + "%");

            // Execute the query
            ResultSet rs = prstmt.executeQuery();

            // Populate the table with the search results
            while (rs.next()) {
                // Retrieve data from the database
                int id = rs.getInt("id");
                String todo = rs.getString("list");
                String subject = rs.getString("subject");
                String dodate = rs.getString("do");
                String deadline = rs.getString("deadline");
                // Add row to the table model
                System.out.println(id + " " + todo + " " + subject + " " + dodate + " " + deadline);
                model.addRow(new Object[]{id, todo, subject, dodate, deadline});

            }
            // Notify user if no records are found
            if (model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "No matching records found!");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error searching records: " + e.getMessage());
        }
    }//GEN-LAST:event_searcharchbtnActionPerformed

    private void backbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbtnMouseClicked
        // TODO add your handling code here:
        try {
                // Query to get the user ID from the setjabbis table
                String query1 = "SELECT * FROM setjabbis";
                PreparedStatement prstmt = con.prepareStatement(query1);
                ResultSet rs1 = prstmt.executeQuery();

                // Check if there are results
                if (rs1.next()) {
                    int userid = rs1.getInt("userid");

                    // Query to get user information from masters_account
                    String query = "SELECT * FROM masters_account WHERE id = ?";
                    PreparedStatement pstmt = con.prepareStatement(query);
                    pstmt.setInt(1, userid);
                    ResultSet rs = pstmt.executeQuery();

                    if (rs.next()) {
                        // Get user details from database
                        String firstName = rs.getString("fname");
                        String lastName = rs.getString("lname");
                        String email = rs.getString("email");  // or username column name

                        // Create new MainWindow1 with user details
                        new MainWindow1(firstName, lastName, email, userid).setVisible(true);
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "User information not found!");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "No user found in setjabbis.");
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
                e.printStackTrace();
            }
    }//GEN-LAST:event_backbtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(archWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(archWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(archWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(archWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatDarkLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new archWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backbtn;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton searcharchbtn;
    private javax.swing.JTextField searchfarch;
    // End of variables declaration//GEN-END:variables
}
