/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assistant_jabbis;
import com.formdev.flatlaf.FlatDarkLaf;
import databaseConnection.databaseConnect;
import java.sql.Connection;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class CreateAccount extends javax.swing.JFrame {
    private Connection con;

    /**
     * Creates new form login
     */
    public CreateAccount() {
        initComponents();
        con = databaseConnect.getConnection();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Emailinput = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lastnameinput = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Savebtn = new javax.swing.JButton();
        Passinput = new javax.swing.JPasswordField();
        Userinput = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        gotologinbtn = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 51));
        jLabel1.setText("lastname:");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        Emailinput.setBackground(new java.awt.Color(60, 63, 65));
        Emailinput.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        Emailinput.setForeground(new java.awt.Color(0, 255, 0));
        Emailinput.setBorder(null);
        Emailinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailinputActionPerformed(evt);
            }
        });
        jPanel2.add(Emailinput, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 283, 30));

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 51));
        jLabel3.setText("Password:");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        lastnameinput.setBackground(new java.awt.Color(60, 63, 65));
        lastnameinput.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        lastnameinput.setForeground(new java.awt.Color(0, 255, 0));
        lastnameinput.setBorder(null);
        lastnameinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastnameinputActionPerformed(evt);
            }
        });
        jPanel2.add(lastnameinput, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 283, 30));

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 51));
        jLabel4.setText("Email:");
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        Savebtn.setBackground(new java.awt.Color(51, 51, 51));
        Savebtn.setFont(new java.awt.Font("Impact", 1, 14)); // NOI18N
        Savebtn.setForeground(new java.awt.Color(51, 255, 51));
        Savebtn.setText("Save");
        Savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavebtnActionPerformed(evt);
            }
        });
        jPanel2.add(Savebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 212, 41));

        Passinput.setBackground(new java.awt.Color(60, 63, 65));
        Passinput.setFont(new java.awt.Font("Impact", 1, 14)); // NOI18N
        Passinput.setForeground(new java.awt.Color(51, 255, 51));
        Passinput.setBorder(null);
        Passinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassinputActionPerformed(evt);
            }
        });
        jPanel2.add(Passinput, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 283, 30));

        Userinput.setBackground(new java.awt.Color(60, 63, 65));
        Userinput.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        Userinput.setForeground(new java.awt.Color(0, 255, 0));
        Userinput.setBorder(null);
        Userinput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserinputActionPerformed(evt);
            }
        });
        jPanel2.add(Userinput, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 283, 30));

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 51));
        jLabel7.setText("Already have an account?");
        jLabel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 255, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 280, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 255, 0));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 280, 30));

        jSeparator3.setForeground(new java.awt.Color(0, 255, 0));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 280, 30));

        jSeparator6.setForeground(new java.awt.Color(0, 255, 0));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 280, 30));

        gotologinbtn.setBackground(new java.awt.Color(51, 51, 51));
        gotologinbtn.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        gotologinbtn.setForeground(new java.awt.Color(0, 255, 0));
        gotologinbtn.setText("LOGIN");
        gotologinbtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        gotologinbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gotologinbtnMouseClicked(evt);
            }
        });
        jPanel2.add(gotologinbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 430, -1, -1));

        jLabel9.setBackground(new java.awt.Color(51, 51, 51));
        jLabel9.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 255, 51));
        jLabel9.setText("firstname");
        jLabel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-registration-96.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 96, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 363, 460));

        jLabel2.setFont(new java.awt.Font("Impact", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 51));
        jLabel2.setText("Create Account");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/favicon2.0.png"))); // NOI18N
        jLabel8.setText("jLabel5");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, 100, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/midbg.jpg"))); // NOI18N
        jLabel10.setText("jLabel7");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 400, 220));

        jLabel11.setFont(new java.awt.Font("Impact", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 255, 51));
        jLabel11.setText("Jabbis voice command Assistant");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 420, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EmailinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailinputActionPerformed

    private void lastnameinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastnameinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastnameinputActionPerformed

    private void SavebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavebtnActionPerformed
        // TODO add your handling code here:
        String Email,passw,fname,lname,query;
        try{
//           Class.forName("com.mysql.cj.jdbc.Driver");

           
           Statement st = con.createStatement();
           
            if ("".equals(Emailinput.getText()) && "".equals(new String(Passinput.getPassword()))) {
            JOptionPane.showMessageDialog(new JFrame(),
                "ADD TODO LIST IS REQUIRED",
                "Dialog",
                JOptionPane.ERROR_MESSAGE);
            }
            else{
                Email = Emailinput.getText();
                passw = new String(Passinput.getPassword());
                fname = Userinput.getText();
                lname = lastnameinput.getText();
                query = "INSERT INTO masters_account(Email,passw,fname,lname)VALUES('"+Email+"','"+passw+"','"+fname+"','"+lname+"')";
                st.executeUpdate(query);
           }
            JOptionPane.showMessageDialog(this,"Account Created Successfuly");

            
        }catch(Exception e){
//            System.out.println("Error"+ e.getMessage());
             JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_SavebtnActionPerformed

    private void PassinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassinputActionPerformed

    private void UserinputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserinputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserinputActionPerformed

    private void gotologinbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gotologinbtnMouseClicked
        // TODO add your handling code here:
        this.dispose();
        new loginwindow().setVisible(true);
        
        
    }//GEN-LAST:event_gotologinbtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        FlatDarkLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Emailinput;
    private javax.swing.JPasswordField Passinput;
    private javax.swing.JButton Savebtn;
    private javax.swing.JTextField Userinput;
    private javax.swing.JLabel gotologinbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField lastnameinput;
    // End of variables declaration//GEN-END:variables
}
