/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assistant_jabbis;
import com.formdev.flatlaf.FlatDarkLaf;
import databaseConnection.databaseConnect;
import java.sql.PreparedStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;

import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class settingWin extends javax.swing.JFrame {
    private int userId;
    private String Fname;
    private String lname;
    private String usernameSession;
    private Connection con;

    /**
     * Creates new form settingWin
     */
    public settingWin(int userid, String fname, String lname, String username) {
        this.userId = userid;
        this.Fname = fname;
        this.lname = lname;
        this.usernameSession = username;
        initComponents();
        con = databaseConnect.getConnection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LASTNAME = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        FIRSTNAME = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        SAVESETTING = new javax.swing.JButton();
        ASSISTANTNAME = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        MIDINITIAL = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        backbtn = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 51));
        jLabel1.setText("FIRSTNAME");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        LASTNAME.setBackground(new java.awt.Color(60, 63, 65));
        LASTNAME.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        LASTNAME.setForeground(new java.awt.Color(0, 255, 0));
        LASTNAME.setBorder(null);
        LASTNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LASTNAMEActionPerformed(evt);
            }
        });
        jPanel2.add(LASTNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 283, 30));

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 51));
        jLabel3.setText("MIDINITIAL");
        jLabel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, -1, -1));

        FIRSTNAME.setBackground(new java.awt.Color(60, 63, 65));
        FIRSTNAME.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        FIRSTNAME.setForeground(new java.awt.Color(0, 255, 0));
        FIRSTNAME.setBorder(null);
        FIRSTNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FIRSTNAMEActionPerformed(evt);
            }
        });
        jPanel2.add(FIRSTNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 283, 30));

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 51));
        jLabel4.setText("LASTNAME");
        jLabel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        SAVESETTING.setBackground(new java.awt.Color(51, 51, 51));
        SAVESETTING.setFont(new java.awt.Font("Impact", 1, 14)); // NOI18N
        SAVESETTING.setForeground(new java.awt.Color(51, 255, 51));
        SAVESETTING.setText("Save");
        SAVESETTING.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SAVESETTINGActionPerformed(evt);
            }
        });
        jPanel2.add(SAVESETTING, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, 212, 41));

        ASSISTANTNAME.setBackground(new java.awt.Color(60, 63, 65));
        ASSISTANTNAME.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        ASSISTANTNAME.setForeground(new java.awt.Color(0, 255, 0));
        ASSISTANTNAME.setBorder(null);
        ASSISTANTNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ASSISTANTNAMEActionPerformed(evt);
            }
        });
        jPanel2.add(ASSISTANTNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 283, 30));

        jSeparator1.setForeground(new java.awt.Color(0, 255, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 280, 30));

        jSeparator2.setForeground(new java.awt.Color(0, 255, 0));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 280, 30));

        jSeparator3.setForeground(new java.awt.Color(0, 255, 0));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 280, 30));

        jSeparator6.setForeground(new java.awt.Color(0, 255, 0));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 280, 30));

        jLabel9.setBackground(new java.awt.Color(51, 51, 51));
        jLabel9.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 255, 51));
        jLabel9.setText("ASSISTANT NAME");
        jLabel9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-registration-96.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 96, -1));

        MIDINITIAL.setBackground(new java.awt.Color(60, 63, 65));
        MIDINITIAL.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        MIDINITIAL.setForeground(new java.awt.Color(0, 255, 0));
        MIDINITIAL.setBorder(null);
        MIDINITIAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIDINITIALActionPerformed(evt);
            }
        });
        jPanel2.add(MIDINITIAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 310, 283, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 363, 460));

        jLabel2.setFont(new java.awt.Font("Impact", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 51));
        jLabel2.setText("SET YOUR ASSISTANT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(51, 255, 51));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1070, 20));

        backbtn.setBackground(new java.awt.Color(51, 51, 51));
        backbtn.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        backbtn.setForeground(new java.awt.Color(0, 255, 0));
        backbtn.setText("BACK");
        backbtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        backbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbtnMouseClicked(evt);
            }
        });
        jPanel1.add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 405, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LASTNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LASTNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LASTNAMEActionPerformed

    private void FIRSTNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FIRSTNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FIRSTNAMEActionPerformed

    private void SAVESETTINGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SAVESETTINGActionPerformed
        // TODO add your handling code here:
        String surname,firstnamae,midinitial,assistant,query;
        try{
            //           Class.forName("com.mysql.cj.jdbc.Driver");

            Connection con = databaseConnect.getConnection();
            Statement st = con.createStatement();

            if ("".equals(LASTNAME.getText()) && "".equals(MIDINITIAL.getText())) {
                JOptionPane.showMessageDialog(new JFrame(),
                    "ADD TODO LIST IS REQUIRED",
                    "Dialog",
                    JOptionPane.ERROR_MESSAGE);
            }
            else{
                surname = LASTNAME.getText();
                midinitial = MIDINITIAL.getText();
                assistant = ASSISTANTNAME.getText();
                firstnamae = FIRSTNAME.getText();
                 query = "UPDATE setjabbis SET " +
                "assistantname = ?, " +
                "username = ?, " +
                "surname = ?, " +
                "midinitial = ?";
                PreparedStatement pst = con.prepareStatement(query);
                pst.setString(1, assistant);
                pst.setString(2, firstnamae);
                pst.setString(3, surname);
                pst.setString(4, midinitial);
                pst.executeUpdate();
            }
            JOptionPane.showMessageDialog(this,"ASSITANT SET Successfuly");

        }catch(Exception e){
            //            System.out.println("Error"+ e.getMessage());
            JOptionPane.showMessageDialog(this,e.getMessage());
        }
    }//GEN-LAST:event_SAVESETTINGActionPerformed

    private void ASSISTANTNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ASSISTANTNAMEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ASSISTANTNAMEActionPerformed

    private void backbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbtnMouseClicked
        // TODO add your handling code here:
        try {
            // Query to get user information
            String query = "SELECT * FROM masters_account WHERE id = ?";
            PreparedStatement pstmt = con.prepareStatement(query);
            pstmt.setInt(1, userId);
            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                // Get user details from database
                String firstName = rs.getString("fname");
                String lastName = rs.getString("lname");
                String email = rs.getString("email");  // or username column name

                // Create new MainWindow1 with user details
                new MainWindow1(firstName, lastName, email, userId).setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "User information not found!");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }

    }//GEN-LAST:event_backbtnMouseClicked

    private void MIDINITIALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIDINITIALActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MIDINITIALActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(settingWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(settingWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(settingWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(settingWin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatDarkLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new settingWin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ASSISTANTNAME;
    private javax.swing.JTextField FIRSTNAME;
    private javax.swing.JTextField LASTNAME;
    private javax.swing.JTextField MIDINITIAL;
    private javax.swing.JButton SAVESETTING;
    private javax.swing.JLabel backbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
