/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assistant_jabbis;
import databaseConnection.databaseConnect;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.text.SimpleDateFormat;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import com.formdev.flatlaf.FlatDarkLaf;
/**
 *
 * @author USER
 */
public class todolistWindow extends javax.swing.JFrame {
    /**
     * Creates new form todolistWindow
     */
    public todolistWindow() {
        initComponents();
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Subject = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        backbtn = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JTextArea();
        DeleteBtn = new javax.swing.JButton();
        doDate = new com.toedter.calendar.JDateChooser();
        DeadlineDate = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SystemAnalysisBtn = new javax.swing.JRadioButton();
        ccnaBtn = new javax.swing.JRadioButton();
        EventDBtn = new javax.swing.JRadioButton();
        advanceDbBtn = new javax.swing.JRadioButton();
        SystemIntegBtn = new javax.swing.JRadioButton();
        webBtn = new javax.swing.JRadioButton();
        SpiBtn = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        CreatelistBtn = new javax.swing.JButton();
        Updatebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setBackground(new java.awt.Color(102, 102, 102));
        jLabel8.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 255, 51));
        jLabel8.setText("ADDING TASK");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        backbtn.setBackground(new java.awt.Color(51, 51, 51));
        backbtn.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        backbtn.setForeground(new java.awt.Color(0, 255, 0));
        backbtn.setText("BACK");
        backbtn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        backbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backbtnMouseClicked(evt);
            }
        });
        jPanel2.add(backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 20, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 60));

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 1080, 20));

        jPanel4.setBackground(new java.awt.Color(102, 102, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        list.setColumns(20);
        list.setRows(5);
        jScrollPane1.setViewportView(list);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 370, 110));

        DeleteBtn.setBackground(new java.awt.Color(51, 51, 51));
        DeleteBtn.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        DeleteBtn.setForeground(new java.awt.Color(51, 255, 51));
        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });
        jPanel4.add(DeleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 410, 250, 34));

        doDate.setBackground(new java.awt.Color(102, 102, 102));
        doDate.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        doDate.setForeground(new java.awt.Color(51, 255, 51));
        jPanel4.add(doDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 240, -1));

        DeadlineDate.setBackground(new java.awt.Color(102, 102, 102));
        DeadlineDate.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        DeadlineDate.setForeground(new java.awt.Color(255, 0, 0));
        jPanel4.add(DeadlineDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 240, -1));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 51));
        jLabel1.setText("Deadline On:");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 80, 30));

        jLabel2.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 51));
        jLabel2.setText("Add your  Task  list here:");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 150, 30));

        jLabel3.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 51));
        jLabel3.setText("Do this On:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 70, 30));

        Subject.add(SystemAnalysisBtn);
        SystemAnalysisBtn.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        SystemAnalysisBtn.setForeground(new java.awt.Color(51, 255, 51));
        SystemAnalysisBtn.setText("System analysis and design");
        jPanel4.add(SystemAnalysisBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        Subject.add(ccnaBtn);
        ccnaBtn.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        ccnaBtn.setForeground(new java.awt.Color(51, 255, 51));
        ccnaBtn.setText("CCNA");
        jPanel4.add(ccnaBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        Subject.add(EventDBtn);
        EventDBtn.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        EventDBtn.setForeground(new java.awt.Color(51, 255, 51));
        EventDBtn.setText("EVENT DRIVEN PROGRAMMING");
        jPanel4.add(EventDBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, -1, -1));

        Subject.add(advanceDbBtn);
        advanceDbBtn.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        advanceDbBtn.setForeground(new java.awt.Color(51, 255, 51));
        advanceDbBtn.setText("Advance database");
        jPanel4.add(advanceDbBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        Subject.add(SystemIntegBtn);
        SystemIntegBtn.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        SystemIntegBtn.setForeground(new java.awt.Color(51, 255, 51));
        SystemIntegBtn.setText("System integration ");
        jPanel4.add(SystemIntegBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, -1, -1));

        Subject.add(webBtn);
        webBtn.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        webBtn.setForeground(new java.awt.Color(51, 255, 51));
        webBtn.setText("Web 2");
        jPanel4.add(webBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        Subject.add(SpiBtn);
        SpiBtn.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        SpiBtn.setForeground(new java.awt.Color(51, 255, 51));
        SpiBtn.setText("Social and profesion issue");
        jPanel4.add(SpiBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "TASK", "Subject", "Do this On", "Deadline"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 60, 620, 340));

        CreatelistBtn.setBackground(new java.awt.Color(51, 51, 51));
        CreatelistBtn.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        CreatelistBtn.setForeground(new java.awt.Color(51, 255, 51));
        CreatelistBtn.setText("Save");
        CreatelistBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatelistBtnActionPerformed(evt);
            }
        });
        jPanel4.add(CreatelistBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 350, 34));

        Updatebtn.setBackground(new java.awt.Color(51, 51, 51));
        Updatebtn.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        Updatebtn.setForeground(new java.awt.Color(51, 255, 51));
        Updatebtn.setText("Update");
        Updatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdatebtnActionPerformed(evt);
            }
        });
        jPanel4.add(Updatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 230, 34));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1080, 510));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
        
            
    }//GEN-LAST:event_DeleteBtnActionPerformed
    

    private void CreatelistBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatelistBtnActionPerformed
        // TODO add your handling code here:
        String tolist, doDate, deadline, Subject;

        try {
            Connection con = databaseConnect.getConnection();
            SimpleDateFormat sdf = new SimpleDateFormat("yy-MM-dd");
            doDate = sdf.format(this.doDate.getDate());
            deadline = sdf.format(this.DeadlineDate.getDate());
            tolist = this.list.getText();

            // Determine the subject based on selected radio button
            if (this.ccnaBtn.isSelected()) {
                Subject = "CCNA";
            } else if (this.webBtn.isSelected()) {
                Subject = "WEB 2";
            } else if (this.advanceDbBtn.isSelected()) {
                Subject = "ADVANCE DATABASE";
            } else if (this.SystemAnalysisBtn.isSelected()) {
                Subject = "SYSTEM ANALYSIS AND DESIGN";
            } else if (this.SystemIntegBtn.isSelected()) {
                Subject = "SYSTEM INTEGRATION";
            } else if (this.EventDBtn.isSelected()) {
                Subject = "EVENT DRIVEN PROGRAMMING";
            } else if (this.SpiBtn.isSelected()) {
                Subject = "SOCIAL AND PROFESSIONAL ISSUE";
            } else {
                JOptionPane.showMessageDialog(this, "Please select a subject.");
                return;
            }

            // Check if any required field is empty
            if (tolist.isEmpty() || doDate.isEmpty() || deadline.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please fill all the fields.");
            } else {
                String query = "INSERT INTO todoList(list, subject, do, deadline) VALUES (?, ?, ?, ?)";
                PreparedStatement pstmt = con.prepareStatement(query);
                pstmt.setString(1, tolist);
                pstmt.setString(2, Subject);
                pstmt.setString(3, doDate);
                pstmt.setString(4, deadline);

                pstmt.executeUpdate();  // Execute the insert statement

                JOptionPane.showMessageDialog(this, "Task added successfully.");
                System.out.println("Insertion successful.");
            }

        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_CreatelistBtnActionPerformed

    private void loadData() {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // Clear existing data

        try {


            Connection con = databaseConnect.getConnection();
            Statement st = con.createStatement();
            String query = "SELECT * FROM todoList";

            ResultSet rs = st.executeQuery(query);

            while (rs.next()) {
                // Retrieve data from the database
                String todo = rs.getString("list");
                String subject = rs.getString("subject");
                String dodate = rs.getString("do");
                String deadline = rs.getString("deadline");

                // Add row to the table model
                model.addRow(new Object[]{todo,subject ,dodate, deadline});
            }

        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }
    private void UpdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdatebtnActionPerformed
        // TODO add your handling code here:
        new MainWindow().setVisible(true);

    }//GEN-LAST:event_UpdatebtnActionPerformed

    private void backbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backbtnMouseClicked
        // TODO add your handling code here:
        new MainWindow1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backbtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(todolistWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(todolistWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(todolistWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(todolistWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        FlatDarkLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new todolistWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreatelistBtn;
    private com.toedter.calendar.JDateChooser DeadlineDate;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JRadioButton EventDBtn;
    private javax.swing.JRadioButton SpiBtn;
    private javax.swing.ButtonGroup Subject;
    private javax.swing.JRadioButton SystemAnalysisBtn;
    private javax.swing.JRadioButton SystemIntegBtn;
    private javax.swing.JButton Updatebtn;
    private javax.swing.JRadioButton advanceDbBtn;
    private javax.swing.JLabel backbtn;
    private javax.swing.JRadioButton ccnaBtn;
    private com.toedter.calendar.JDateChooser doDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea list;
    private javax.swing.JRadioButton webBtn;
    // End of variables declaration//GEN-END:variables


}
